import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar></NavBar>
        <main className="px-8 py-20 max-w-6xl mx-auto"> {children} </main>
      </body>
    </html>
  );
}
